### ISSUE TITLE
[API] Voting

### ISSUE THREAD

**Issue by lucasmontano** [lucasmontano/magic-link#10]
As a user, I want to be able to vote in an ongoing poll.

**User**
A user is anyone that has access to the API and it's identified by an e-mail.

**Vote Options**
In a ranked poll, the user has the right to vote in multiple options. The options should be sent sorted by preference. 

Example: `["my best option", "second best option", "third best option"]`

**Validation**
The API should check if all informed options are available in the current poll.

Example: 
- Valid options `["PHP", "JAVA", "JS"]` 
- Informed options `["VB", "PHP"]`
- Error: VB is not a valid option

**API Request**
```
{
  "identifier": "email@domain.com",
  "options": ["VB", JAVA"]
}
```

**API Response**
Code: The API should return 204 status code if the vote is accepted and 400 if the request is invalid.
Body: The API should return an error message or empty body (if succeed).

**Error message**
```
{
    "detail": {
        "message": "You are trying to vote in one or more invalid options, please check the available options.",
        "options": [
            "VB",
            "COBOL",
            "Delphi"
        ]
    }
}
```

**Tech Implementation**
The vote is added to the Redis queue and should be consumed by the Confirmation Service #11 .

**Comment by jbarbosaamancio** [comment]
The memory queue with Python RQ may be made with BackgroundTask which is descript in the FastAPI Documentation would be a good idea get see
