### ISSUE TITLE
[Service] Vote Confirmation

### ISSUE THREAD

**Issue by lucasmontano** [lucasmontano/magic-link#11]
As a user that sent its vote, I should be able to confirm my identification.

All votes received from #10 should be confirmed by a magic link. This service should consume the Queue as FIFO (First In First Out).

**Comment by jbarbosaamancio** [comment]
the function below generate a link with hash of identifier which may be send to vote confirmation i wait that help
` def generateLink(vote: Vote):
        hash = sha256(vote.identifier.encode()).hexdigest()
        return f'127.0.0.1:8000/{hash}'`

**Comment by lucasmontano** [comment]
As we're changing the project scope, this issue is no longer necessary.
