### ISSUE TITLE
[API] Vote confirmation

### ISSUE THREAD

**Issue by lucasmontano** [lucasmontano/magic-link#12]
As a user that has voted, I should be able to confirm my new vote.

The user will receive the magic link sent by the Confirmation Service #11 , the link is a GET request to this API.

A user can vote multiple times, but the last vote will override the previous ones. This API should write in the database the computed vote. 

**API Endpoint:** /vote/confirmation/JWT

**API Response**
The API should return 200 status code if the vote is accepted and 400 if the request is invalid.

Note: we can create a separated issue to redirect the user to a cool webpage :)

**Comment by jbarbosaamancio** [comment]
Use pyjwt which give an interface complete for work with JWT is much easy

**Comment by lucasmontano** [comment]
As we're changing the project scope, this issue is no longer necessary.
