### ISSUE TITLE
Choosing a proper framework

### ISSUE THREAD

**Issue by ArthurFleischman** [lucasmontano/magic-link#2]
i though in 2 options:
- flask : light and fast, looks like the express in JS
- Django: heavier but more complete, looks like the GIN in golang(My stack)

**Comment by HenriqueDerosa** [comment]
Django has a good cms automatically integrated, in the company I work they use django, and we've access to this cms, pretty helpful for FrontEnd Integration. 
I'm not sure but I think it has also an easy way to do a CRUD (or automatic, not sure). And we can improve the CRUD as well. 
> Not sure, of anything cause this is a `stack que não domino` as well 😝

**Comment by ArthurFleischman** [comment]
> Django has a good cms automatically integrated, in the company I work they use django, and we've access to this cms, pretty helpful for FrontEnd Integration.
> I'm not sure but I think it has also an easy way to do a CRUD (or automatic, not sure). And we can improve the CRUD as well.
> 
> > Not sure, of anything cause this is a `stack que não domino` as well stuck_out_tongue_closed_eyes

im not a python to web expert to hahha, but im not totally lost.... lets learn together !

**Comment by luizfspjf** [comment]
I recommend to use Flask I think it fits better with `uma stack que não domino `
As the PEP 20
`Simple is better than complex.`
[https://www.python.org/dev/peps/pep-0020/](url)

**Comment by thiagobeppe** [comment]
I recommend to use Flask too, because it is a microframework and we only will make a backend, so we can only put in the project what we want.

**Comment by nataneb32** [comment]
Yep, flask is much simpler than Django.

**Comment by ArthurFleischman** [comment]
so, i think we need more "corum" but flash is pretty the reasonable option.... @lucasmontano your turn admin...

**Comment by ArthurFleischman** [comment]
@lucasmontano if you could, allow labels... it could help a lot

**Comment by Wedz0ff** [comment]
I think it's good to use Flask on this project, since it's much more simpler, as others said.

**Comment by jbarbosaamancio** [comment]
Flask is much simple, and surely ideal for this project in my opinion.

**Comment by daviziks** [comment]
Flask is the best option because Django is designed for more experienced python programmers. Not criticizing you Lucas, but it is better to start with the simplest, just like you did with Node.js using Express instead of Adonis.

**Comment by lucasmontano** [comment]
Let’s keep the requirements as simple as possible in this project. No frontend needed it. After delivering the APIs and the ranking algorithm. What do you think about fastAPI framework?

**Comment by thiagobeppe** [comment]
Bringing the discussion on discord from here. FastAPI when compared with Flask is a better choice because your asynchronous behavior and more clean framework. All of the features in flask is covered by fastAPI

**Comment by lucasmontano** [comment]
https://www.slant.co/versus/1398/34241/~flask_vs_fastapi

Flask is HTML-oriented, not API-oriented... I think fastAPI sounds like a better choice here indeed

**Comment by thiagobeppe** [comment]
https://www.quora.com/What-are-the-advantages-of-using-FastAPI-over-flask

**Comment by thiagobeppe** [comment]
Another link for aggregate infos in the discussion

**Comment by ArthurFleischman** [comment]
> https://www.slant.co/versus/1398/34241/~flask_vs_fastapi
> 
> Flask is HTML-oriented, not API-oriented... I think fastAPI sounds like a better choice here indeed

By what a had seen, people use flask for apis

**Comment by ArthurFleischman** [comment]
@lucasmontano https://nordicapis.com/8-open-source-frameworks-for-building-apis-in-python

Above a list with the 8 most popular python framework for that..

**Comment by lucasmontano** [comment]
> @lucasmontano https://nordicapis.com/8-open-source-frameworks-for-building-apis-in-python
> 
> 
> 
> Above a list with the 8 most popular python framework for that..

Thanks! My only concern with Flask is that it’s relying on WSGI. What do you think about WSGI limitations?

**Comment by ArthurFleischman** [comment]
For real, i just know that's not good for production, I never used it for real projects... just tried for fun...

**Comment by ArthurFleischman** [comment]
So, I don't have enough knowledge for answer this question...

**Comment by joao-cabral** [comment]
Flask is much simple, better choice for this project

**Comment by Wedz0ff** [comment]
> Let’s keep the requirements as simple as possible in this project. No frontend needed it. After delivering the APIs and the ranking algorithm. What do you think about fastAPI framework?

Let's use it then, it's gonna be an awesome oportunity to learn it :)

**Comment by ianfreitas1** [comment]
I work with Django building an api with Django Rest Framework. Never used Flask, but I think Django is really powerful and easy once you get the hang of it. With just few lines of code you can create a basic CRUD, you just have to do everything in the Django way and then it's just getting used to the same flow.

**Comment by rpenna** [comment]
As a dev who works with django, I think it's too complex for this project. I've never worked with flask or fastAPI, but I would say that they're more appropriated alternatives.

**Comment by jbarbosaamancio** [comment]
It seems that we're between FastAPI and Flask. Or already choice the framework?

**Comment by rochacbruno** [comment]
Flask ou FastAPI!

No meu canal tenho uma playlist de Flask https://YouTube.com/CodeShowBR

**Comment by thiagobeppe** [comment]
I did some tests in FastAPI and the swagger by default for our project will be good, because all the routes will be documented without much efforts

**Comment by felipemarkson** [comment]
Flask is simple and it has more examples and tutorials.
I think it is the better choice for this project

**Comment by lucasmontano** [comment]
> I did some tests in FastAPI and the swagger by default for our project will be good, because all the routes will be documented without much efforts

yeah, the default documentation will be super nice and will save a lot of time

**Comment by thiagobeppe** [comment]
> It seems that we're between FastAPI and Flask. Or already choice the framework?

if you have any other framework to propose, please, post here. We will evaluate the pros and cons in live.

**Comment by lucasmontano** [comment]
we decided to go with [FastAPI](https://fastapi.tiangolo.com/) the main reason: FastAPI provide Swagger doc by default.
