### ISSUE TITLE
Ranked Voting Computation

### ISSUE THREAD

**Issue by lucasmontano** [lucasmontano/magic-link#4]
Write the algorithm to evaluate the winner in a ranked voting.

https://en.m.wikipedia.org/wiki/Instant-runoff_voting

**Comment by jbarbosaamancio** [comment]
I have a pdf excellent which explain about [voting systems](https://drive.google.com/file/d/1bOGS0jkPyMP1Cx_-Vr7kI12-MwG4C-rS/view?usp=sharing)  I'll leave here to consult

**Comment by jbarbosaamancio** [comment]
how would work this algorithm?

**Comment by lucasmontano** [comment]
As we're changing the project scope, this issue is no longer necessary.
