### ISSUE TITLE
Message Broker

### ISSUE THREAD

**Issue by lucasmontano** [lucasmontano/magic-link#5]
Decide which message broker we should use for queuing the votes: RabbitMQ, Redis or others?

**Comment by ArthurFleischman** [comment]
i never used an message broker, why would we use it?, if its to basic, i can search.... not a problem

**Comment by lucasmontano** [comment]
I think we need In order to process multiple requests, normalize the data and implement pub/sub. 

Not sure how much we need to use its cache, but if we need, Redis also would be a nice option. 

As I’m not a backend developer, I would not rely only on this comment 😁

**Comment by ArthurFleischman** [comment]
pub/sub so it uses mqtt protocol?

**Comment by omurilo** [comment]
I think a messaging broker for this project can sweat like a cannon to kill an ant, I think a simple socket tool can solve it, but if I were to use a broker I would use RabbitMQ.

**Comment by lucasmontano** [comment]
Not sure why do you think a socket is important here, maybe I’m missing something. 

We need to dispatch messages if we want to work with multiple services without reading and writing in a database.

**Comment by thiagobeppe** [comment]
I've never worked with RabbitMQ or Redis with MsgBroker, but the kafka docs from python are very clean and don't have much effort to work with it. I've used the kafka-python lib.

**Comment by rochacbruno** [comment]
If you decide to go with FastAPI there is an example here: https://iwpnd.pw/articles/2020-03/apache-kafka-fastapi-geostream

**Comment by rochacbruno** [comment]
@lucasmontano take a look on https://dramatiq.io/ or https://python-rq.org/

**Comment by lucasmontano** [comment]
As @rochacbruno suggested we're going with [PythonRQ with Redis](https://python-rq.org/patterns/)
